name: 'Execução Manual'

on: 
  workflow_dispatch: 

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando repositório do projeto
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando Mocha
        run: npm install -g mocha

      - name: Instalação das dependências do projeto
        run: npm install

      - name: Execução dos testes unitários com Mocha
        run: npm test

