name: 'Execução Agendada'

on: 
  schedule: 
    - cron: '1 22 * * 0'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando repositório do projeto
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Execução dos testes unitários 
        run: yarn test